package com.github.medavox.ipa

import com.github.medavox.ipa.Manner.*
import com.github.medavox.ipa.Place.*

enum class Manner {
    STOP_PLOSIVE,
    NASAL,
    FRICATIVE,
    APPROXIMANT,
    TAP_OR_FLAP,
    TRILL,
    LATERAL_FRICATIVE,
    LATERAL_APPROXIMANT,
    LATERAL_TAP_FLAP,


}

enum class Place {
    //labial
    BILABIAL,
    LABIO_DENTAL,
    LINGUO_LABIAL,

    //coronal
    DENTAL,
    ALVEOLAR,
    POST_ALVEOLAR,
    RETROFLEX,

    //dorsal
    PALATAL,
    VELAR,
    UVULAR,

    //laryngeal
    PHARYNGEAL_EPIGLOTTAL,
    GLOTTAL
}

enum class PulmonicConsonants(ipaSymbol:String,
                              placeOfArticulation:Place,
                              mannerOfArticulation:Manner,
                              voiced:Boolean=false) {
    //not all of these combinations are valid consonants


    //BILABIALS
    //=========
    VOICELESS_BILABIAL_STOP_PLOSIVE("p", BILABIAL, STOP_PLOSIVE, false),
    VOICED_BILABIAL_STOP_PLOSIVE("b", BILABIAL, STOP_PLOSIVE, true),


    VOICELESS_BILABIAL_NASAL("̥m", BILABIAL, NASAL),
    VOICED_BILABIAL_NASAL("m", BILABIAL, NASAL, true),

    VOICELESS_BILABIAL_FRICATIVE("ɸ", BILABIAL, FRICATIVE),
    VOICED_BILABIAL_FRICATIVE("β", BILABIAL, FRICATIVE, true),

    //these are blank on the IPA chart; maybe they can be represented using an existing character + a diacritic?
    //VOICELESS_BILABIAL_APPROXIMANT("", BILABIAL, APPROXIMANT),
    //VOICED_BILABIAL_APPROXIMANT("", BILABIAL, APPROXIMANT, true),

    //VOICELESS_BILABIAL_TAP_OR_FLAP("", BILABIAL, TAP_OR_FLAP),
    //VOICED_BILABIAL_TAP_OR_FLAP("", BILABIAL, TAP_OR_FLAP, true),

    VOICELESS_BILABIAL_TRILL("̥ʙ", BILABIAL, TRILL),
    VOICED_BILABIAL_TRILL("ʙ", BILABIAL, TRILL, true),

    //judged to be impossible
    //VOICELESS_BILABIAL_LATERAL_FRICATIVE("", BILABIAL, LATERAL_FRICATIVE),
    //VOICED_BILABIAL_LATERAL_FRICATIVE("", BILABIAL, LATERAL_FRICATIVE, true),

    //VOICELESS_BILABIAL_LATERAL_APPROXIMANT("", BILABIAL, LATERAL_APPROXIMANT),
    //VOICED_BILABIAL_LATERAL_APPROXIMANT("", BILABIAL, LATERAL_APPROXIMANT, true),

    //VOICELESS_BILABIAL_LATERAL_TAP_FLAP("", BILABIAL, LATERAL_TAP_FLAP),
    //VOICED_BILABIAL_LATERAL_TAP_FLAP("", BILABIAL, LATERAL_TAP_FLAP, true),

    //LABIO-DENTALS
    //=============
    VOICELESS_LABIO_DENTAL_STOP_PLOSIVE("̪p", LABIO_DENTAL, STOP_PLOSIVE),
    VOICED_LABIO_DENTAL_STOP_PLOSIVE("̪b", LABIO_DENTAL, STOP_PLOSIVE, true),

    //VOICELESS_LABIO_DENTAL_NASAL("", LABIO_DENTAL, NASAL),//blank
    VOICED_LABIO_DENTAL_NASAL("ɱ", LABIO_DENTAL, NASAL, true),

    VOICELESS_LABIO_DENTAL_FRICATIVE("f", LABIO_DENTAL, FRICATIVE),
    VOICED_LABIO_DENTAL_FRICATIVE("v", LABIO_DENTAL, FRICATIVE, true),

    VOICELESS_LABIO_DENTAL_APPROXIMANT("̥ʋ", LABIO_DENTAL, APPROXIMANT),
    VOICED_LABIO_DENTAL_APPROXIMANT("ʋ", LABIO_DENTAL, APPROXIMANT, true),

    //VOICELESS_LABIO_DENTAL_TAP_OR_FLAP("", LABIO_DENTAL, TAP_OR_FLAP),//blank
    VOICED_LABIO_DENTAL_TAP_OR_FLAP("ⱱ", LABIO_DENTAL, TAP_OR_FLAP, true),

    //blank on IPA chart
    //VOICELESS_LABIO_DENTAL_TRILL("", LABIO_DENTAL, TRILL),
    //VOICED_LABIO_DENTAL_TRILL("", LABIO_DENTAL, TRILL, true),

    //judged to be impossible
    //VOICELESS_LABIO_DENTAL_LATERAL_FRICATIVE("", LABIO_DENTAL, LATERAL_FRICATIVE),
    //VOICED_LABIO_DENTAL_LATERAL_FRICATIVE("", LABIO_DENTAL, LATERAL_FRICATIVE, true),

    //VOICELESS_LABIO_DENTAL_LATERAL_APPROXIMANT("", LABIO_DENTAL, LATERAL_APPROXIMANT),
    //VOICED_LABIO_DENTAL_LATERAL_APPROXIMANT("", LABIO_DENTAL, LATERAL_APPROXIMANT, true),

    //VOICELESS_LABIO_DENTAL_LATERAL_TAP_FLAP("", LABIO_DENTAL, LATERAL_TAP_FLAP),
    //VOICED_LABIO_DENTAL_LATERAL_TAP_FLAP("", LABIO_DENTAL, LATERAL_TAP_FLAP, true),

    //LINGUO-LABIALS
    //==============
    VOICELESS_LINGUO_LABIAL_STOP_PLOSIVE("̼t", LINGUO_LABIAL, STOP_PLOSIVE),
    VOICED_LINGUO_LABIAL_STOP_PLOSIVE("̼d", LINGUO_LABIAL, STOP_PLOSIVE, true),

    //VOICELESS_LINGUO_LABIAL_NASAL("", LINGUO_LABIAL, NASAL),//blank
    VOICED_LINGUO_LABIAL_NASAL("̼n", LINGUO_LABIAL, NASAL, true),

    VOICELESS_LINGUO_LABIAL_FRICATIVE("̼θ", LINGUO_LABIAL, FRICATIVE),
    VOICED_LINGUO_LABIAL_FRICATIVE("̼ð", LINGUO_LABIAL, FRICATIVE, true),

    //VOICELESS_LINGUO_LABIAL_APPROXIMANT("", LINGUO_LABIAL, APPROXIMANT),//blank
    //VOICED_LINGUO_LABIAL_APPROXIMANT("", LINGUO_LABIAL, APPROXIMANT, true),//blank

    //VOICELESS_LINGUO_LABIAL_TAP_OR_FLAP("", LINGUO_LABIAL, TAP_OR_FLAP),//blank
    VOICED_LINGUO_LABIAL_TAP_OR_FLAP("̼ɾ", LINGUO_LABIAL, TAP_OR_FLAP, true),

    //blank on IPA chart
    //VOICELESS_LINGUO_LABIAL_TRILL("", LINGUO_LABIAL, TRILL),
    //VOICED_LINGUO_LABIAL_TRILL("", LINGUO_LABIAL, TRILL, true),

    //VOICELESS_LINGUO_LABIAL_LATERAL_FRICATIVE("", LINGUO_LABIAL, LATERAL_FRICATIVE),
    //VOICED_LINGUO_LABIAL_LATERAL_FRICATIVE("", LINGUO_LABIAL, LATERAL_FRICATIVE, true),

    //VOICELESS_LINGUO_LABIAL_LATERAL_APPROXIMANT("", LINGUO_LABIAL, LATERAL_APPROXIMANT),
    //VOICED_LINGUO_LABIAL_LATERAL_APPROXIMANT("", LINGUO_LABIAL, LATERAL_APPROXIMANT, true),

    //VOICELESS_LINGUO_LABIAL_LATERAL_TAP_FLAP("", LINGUO_LABIAL, LATERAL_TAP_FLAP),
    //VOICED_LINGUO_LABIAL_LATERAL_TAP_FLAP("", LINGUO_LABIAL, LATERAL_TAP_FLAP, true),

    VOICELESS_DENTAL_STOP_PLOSIVE("t", DENTAL, STOP_PLOSIVE),
    VOICED_DENTAL_STOP_PLOSIVE("d", DENTAL, STOP_PLOSIVE, true),

    VOICELESS_DENTAL_NASAL("̥n", DENTAL, NASAL),
    VOICED_DENTAL_NASAL("n", DENTAL, NASAL, true),

    VOICELESS_DENTAL_FRICATIVE("s", DENTAL, FRICATIVE),
    VOICED_DENTAL_FRICATIVE("z", DENTAL, FRICATIVE, true),

    VOICELESS_DENTAL_APPROXIMANT("", DENTAL, APPROXIMANT),
    VOICED_DENTAL_APPROXIMANT("", DENTAL, APPROXIMANT, true),

    VOICELESS_DENTAL_TAP_OR_FLAP("", DENTAL, TAP_OR_FLAP),
    VOICED_DENTAL_TAP_OR_FLAP("", DENTAL, TAP_OR_FLAP, true),

    VOICELESS_DENTAL_TRILL("", DENTAL, TRILL),
    VOICED_DENTAL_TRILL("", DENTAL, TRILL, true),

    VOICELESS_DENTAL_LATERAL_FRICATIVE("", DENTAL, LATERAL_FRICATIVE),
    VOICED_DENTAL_LATERAL_FRICATIVE("", DENTAL, LATERAL_FRICATIVE, true),

    VOICELESS_DENTAL_LATERAL_APPROXIMANT("", DENTAL, LATERAL_APPROXIMANT),
    VOICED_DENTAL_LATERAL_APPROXIMANT("", DENTAL, LATERAL_APPROXIMANT, true),

    VOICELESS_DENTAL_LATERAL_TAP_FLAP("", DENTAL, LATERAL_TAP_FLAP),
    VOICED_DENTAL_LATERAL_TAP_FLAP("", DENTAL, LATERAL_TAP_FLAP, true),

    VOICELESS_ALVEOLAR_STOP_PLOSIVE("", ALVEOLAR, STOP_PLOSIVE),
    VOICED_ALVEOLAR_STOP_PLOSIVE("", ALVEOLAR, STOP_PLOSIVE, true),

    VOICELESS_ALVEOLAR_NASAL("", ALVEOLAR, NASAL),
    VOICED_ALVEOLAR_NASAL("", ALVEOLAR, NASAL, true),

    VOICELESS_ALVEOLAR_FRICATIVE("", ALVEOLAR, FRICATIVE),
    VOICED_ALVEOLAR_FRICATIVE("", ALVEOLAR, FRICATIVE, true),

    VOICELESS_ALVEOLAR_APPROXIMANT("", ALVEOLAR, APPROXIMANT),
    VOICED_ALVEOLAR_APPROXIMANT("", ALVEOLAR, APPROXIMANT, true),

    VOICELESS_ALVEOLAR_TAP_OR_FLAP("", ALVEOLAR, TAP_OR_FLAP),
    VOICED_ALVEOLAR_TAP_OR_FLAP("", ALVEOLAR, TAP_OR_FLAP, true),

    VOICELESS_ALVEOLAR_TRILL("", ALVEOLAR, TRILL),
    VOICED_ALVEOLAR_TRILL("", ALVEOLAR, TRILL, true),

    VOICELESS_ALVEOLAR_LATERAL_FRICATIVE("", ALVEOLAR, LATERAL_FRICATIVE),
    VOICED_ALVEOLAR_LATERAL_FRICATIVE("", ALVEOLAR, LATERAL_FRICATIVE, true),

    VOICELESS_ALVEOLAR_LATERAL_APPROXIMANT("", ALVEOLAR, LATERAL_APPROXIMANT),
    VOICED_ALVEOLAR_LATERAL_APPROXIMANT("", ALVEOLAR, LATERAL_APPROXIMANT, true),

    VOICELESS_ALVEOLAR_LATERAL_TAP_FLAP("", ALVEOLAR, LATERAL_TAP_FLAP),
    VOICED_ALVEOLAR_LATERAL_TAP_FLAP("", ALVEOLAR, LATERAL_TAP_FLAP, true),

    VOICELESS_POST_ALVEOLAR_STOP_PLOSIVE("", POST_ALVEOLAR, STOP_PLOSIVE),
    VOICED_POST_ALVEOLAR_STOP_PLOSIVE("", POST_ALVEOLAR, STOP_PLOSIVE, true),

    VOICELESS_POST_ALVEOLAR_NASAL("", POST_ALVEOLAR, NASAL),
    VOICED_POST_ALVEOLAR_NASAL("", POST_ALVEOLAR, NASAL, true),

    VOICELESS_POST_ALVEOLAR_FRICATIVE("", POST_ALVEOLAR, FRICATIVE),
    VOICED_POST_ALVEOLAR_FRICATIVE("", POST_ALVEOLAR, FRICATIVE, true),

    VOICELESS_POST_ALVEOLAR_APPROXIMANT("", POST_ALVEOLAR, APPROXIMANT),
    VOICED_POST_ALVEOLAR_APPROXIMANT("", POST_ALVEOLAR, APPROXIMANT, true),

    VOICELESS_POST_ALVEOLAR_TAP_OR_FLAP("", POST_ALVEOLAR, TAP_OR_FLAP),
    VOICED_POST_ALVEOLAR_TAP_OR_FLAP("", POST_ALVEOLAR, TAP_OR_FLAP, true),

    VOICELESS_POST_ALVEOLAR_TRILL("", POST_ALVEOLAR, TRILL),
    VOICED_POST_ALVEOLAR_TRILL("", POST_ALVEOLAR, TRILL, true),

    VOICELESS_POST_ALVEOLAR_LATERAL_FRICATIVE("", POST_ALVEOLAR, LATERAL_FRICATIVE),
    VOICED_POST_ALVEOLAR_LATERAL_FRICATIVE("", POST_ALVEOLAR, LATERAL_FRICATIVE, true),

    VOICELESS_POST_ALVEOLAR_LATERAL_APPROXIMANT("", POST_ALVEOLAR, LATERAL_APPROXIMANT),
    VOICED_POST_ALVEOLAR_LATERAL_APPROXIMANT("", POST_ALVEOLAR, LATERAL_APPROXIMANT, true),

    VOICELESS_POST_ALVEOLAR_LATERAL_TAP_FLAP("", POST_ALVEOLAR, LATERAL_TAP_FLAP),
    VOICED_POST_ALVEOLAR_LATERAL_TAP_FLAP("", POST_ALVEOLAR, LATERAL_TAP_FLAP, true),

    VOICELESS_RETROFLEX_STOP_PLOSIVE("", RETROFLEX, STOP_PLOSIVE),
    VOICED_RETROFLEX_STOP_PLOSIVE("", RETROFLEX, STOP_PLOSIVE, true),

    VOICELESS_RETROFLEX_NASAL("", RETROFLEX, NASAL),
    VOICED_RETROFLEX_NASAL("", RETROFLEX, NASAL, true),

    VOICELESS_RETROFLEX_FRICATIVE("", RETROFLEX, FRICATIVE),
    VOICED_RETROFLEX_FRICATIVE("", RETROFLEX, FRICATIVE, true),

    VOICELESS_RETROFLEX_APPROXIMANT("", RETROFLEX, APPROXIMANT),
    VOICED_RETROFLEX_APPROXIMANT("", RETROFLEX, APPROXIMANT, true),

    VOICELESS_RETROFLEX_TAP_OR_FLAP("", RETROFLEX, TAP_OR_FLAP),
    VOICED_RETROFLEX_TAP_OR_FLAP("", RETROFLEX, TAP_OR_FLAP, true),

    VOICELESS_RETROFLEX_TRILL("", RETROFLEX, TRILL),
    VOICED_RETROFLEX_TRILL("", RETROFLEX, TRILL, true),

    VOICELESS_RETROFLEX_LATERAL_FRICATIVE("", RETROFLEX, LATERAL_FRICATIVE),
    VOICED_RETROFLEX_LATERAL_FRICATIVE("", RETROFLEX, LATERAL_FRICATIVE, true),

    VOICELESS_RETROFLEX_LATERAL_APPROXIMANT("", RETROFLEX, LATERAL_APPROXIMANT),
    VOICED_RETROFLEX_LATERAL_APPROXIMANT("", RETROFLEX, LATERAL_APPROXIMANT, true),

    VOICELESS_RETROFLEX_LATERAL_TAP_FLAP("", RETROFLEX, LATERAL_TAP_FLAP),
    VOICED_RETROFLEX_LATERAL_TAP_FLAP("", RETROFLEX, LATERAL_TAP_FLAP, true),

    VOICELESS_PALATAL_STOP_PLOSIVE("", PALATAL, STOP_PLOSIVE),
    VOICED_PALATAL_STOP_PLOSIVE("", PALATAL, STOP_PLOSIVE, true),

    VOICELESS_PALATAL_NASAL("", PALATAL, NASAL),
    VOICED_PALATAL_NASAL("", PALATAL, NASAL, true),

    VOICELESS_PALATAL_FRICATIVE("", PALATAL, FRICATIVE),
    VOICED_PALATAL_FRICATIVE("", PALATAL, FRICATIVE, true),

    VOICELESS_PALATAL_APPROXIMANT("", PALATAL, APPROXIMANT),
    VOICED_PALATAL_APPROXIMANT("", PALATAL, APPROXIMANT, true),

    VOICELESS_PALATAL_TAP_OR_FLAP("", PALATAL, TAP_OR_FLAP),
    VOICED_PALATAL_TAP_OR_FLAP("", PALATAL, TAP_OR_FLAP, true),

    VOICELESS_PALATAL_TRILL("", PALATAL, TRILL),
    VOICED_PALATAL_TRILL("", PALATAL, TRILL, true),

    VOICELESS_PALATAL_LATERAL_FRICATIVE("", PALATAL, LATERAL_FRICATIVE),
    VOICED_PALATAL_LATERAL_FRICATIVE("", PALATAL, LATERAL_FRICATIVE, true),

    VOICELESS_PALATAL_LATERAL_APPROXIMANT("", PALATAL, LATERAL_APPROXIMANT),
    VOICED_PALATAL_LATERAL_APPROXIMANT("", PALATAL, LATERAL_APPROXIMANT, true),

    VOICELESS_PALATAL_LATERAL_TAP_FLAP("", PALATAL, LATERAL_TAP_FLAP),
    VOICED_PALATAL_LATERAL_TAP_FLAP("", PALATAL, LATERAL_TAP_FLAP, true),

    VOICELESS_VELAR_STOP_PLOSIVE("", VELAR, STOP_PLOSIVE),
    VOICED_VELAR_STOP_PLOSIVE("", VELAR, STOP_PLOSIVE, true),

    VOICELESS_VELAR_NASAL("", VELAR, NASAL),
    VOICED_VELAR_NASAL("", VELAR, NASAL, true),

    VOICELESS_VELAR_FRICATIVE("", VELAR, FRICATIVE),
    VOICED_VELAR_FRICATIVE("", VELAR, FRICATIVE, true),

    VOICELESS_VELAR_APPROXIMANT("", VELAR, APPROXIMANT),
    VOICED_VELAR_APPROXIMANT("", VELAR, APPROXIMANT, true),

    VOICELESS_VELAR_TAP_OR_FLAP("", VELAR, TAP_OR_FLAP),
    VOICED_VELAR_TAP_OR_FLAP("", VELAR, TAP_OR_FLAP, true),

    VOICELESS_VELAR_TRILL("", VELAR, TRILL),
    VOICED_VELAR_TRILL("", VELAR, TRILL, true),

    VOICELESS_VELAR_LATERAL_FRICATIVE("", VELAR, LATERAL_FRICATIVE),
    VOICED_VELAR_LATERAL_FRICATIVE("", VELAR, LATERAL_FRICATIVE, true),

    VOICELESS_VELAR_LATERAL_APPROXIMANT("", VELAR, LATERAL_APPROXIMANT),
    VOICED_VELAR_LATERAL_APPROXIMANT("", VELAR, LATERAL_APPROXIMANT, true),

    VOICELESS_VELAR_LATERAL_TAP_FLAP("", VELAR, LATERAL_TAP_FLAP),
    VOICED_VELAR_LATERAL_TAP_FLAP("", VELAR, LATERAL_TAP_FLAP, true),

    VOICELESS_UVULAR_STOP_PLOSIVE("", UVULAR, STOP_PLOSIVE),
    VOICED_UVULAR_STOP_PLOSIVE("", UVULAR, STOP_PLOSIVE, true),

    VOICELESS_UVULAR_NASAL("", UVULAR, NASAL),
    VOICED_UVULAR_NASAL("", UVULAR, NASAL, true),

    VOICELESS_UVULAR_FRICATIVE("", UVULAR, FRICATIVE),
    VOICED_UVULAR_FRICATIVE("", UVULAR, FRICATIVE, true),

    VOICELESS_UVULAR_APPROXIMANT("", UVULAR, APPROXIMANT),
    VOICED_UVULAR_APPROXIMANT("", UVULAR, APPROXIMANT, true),

    VOICELESS_UVULAR_TAP_OR_FLAP("", UVULAR, TAP_OR_FLAP),
    VOICED_UVULAR_TAP_OR_FLAP("", UVULAR, TAP_OR_FLAP, true),

    VOICELESS_UVULAR_TRILL("", UVULAR, TRILL),
    VOICED_UVULAR_TRILL("", UVULAR, TRILL, true),

    VOICELESS_UVULAR_LATERAL_FRICATIVE("", UVULAR, LATERAL_FRICATIVE),
    VOICED_UVULAR_LATERAL_FRICATIVE("", UVULAR, LATERAL_FRICATIVE, true),

    VOICELESS_UVULAR_LATERAL_APPROXIMANT("", UVULAR, LATERAL_APPROXIMANT),
    VOICED_UVULAR_LATERAL_APPROXIMANT("", UVULAR, LATERAL_APPROXIMANT, true),

    VOICELESS_UVULAR_LATERAL_TAP_FLAP("", UVULAR, LATERAL_TAP_FLAP),
    VOICED_UVULAR_LATERAL_TAP_FLAP("", UVULAR, LATERAL_TAP_FLAP, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_STOP_PLOSIVE("", PHARYNGEAL_EPIGLOTTAL, STOP_PLOSIVE),
    VOICED_PHARYNGEAL_EPIGLOTTAL_STOP_PLOSIVE("", PHARYNGEAL_EPIGLOTTAL, STOP_PLOSIVE, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_NASAL("", PHARYNGEAL_EPIGLOTTAL, NASAL),
    VOICED_PHARYNGEAL_EPIGLOTTAL_NASAL("", PHARYNGEAL_EPIGLOTTAL, NASAL, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_FRICATIVE("", PHARYNGEAL_EPIGLOTTAL, FRICATIVE),
    VOICED_PHARYNGEAL_EPIGLOTTAL_FRICATIVE("", PHARYNGEAL_EPIGLOTTAL, FRICATIVE, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_APPROXIMANT("", PHARYNGEAL_EPIGLOTTAL, APPROXIMANT),
    VOICED_PHARYNGEAL_EPIGLOTTAL_APPROXIMANT("", PHARYNGEAL_EPIGLOTTAL, APPROXIMANT, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_TAP_OR_FLAP("", PHARYNGEAL_EPIGLOTTAL, TAP_OR_FLAP),
    VOICED_PHARYNGEAL_EPIGLOTTAL_TAP_OR_FLAP("", PHARYNGEAL_EPIGLOTTAL, TAP_OR_FLAP, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_TRILL("", PHARYNGEAL_EPIGLOTTAL, TRILL),
    VOICED_PHARYNGEAL_EPIGLOTTAL_TRILL("", PHARYNGEAL_EPIGLOTTAL, TRILL, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_LATERAL_FRICATIVE("", PHARYNGEAL_EPIGLOTTAL, LATERAL_FRICATIVE),
    VOICED_PHARYNGEAL_EPIGLOTTAL_LATERAL_FRICATIVE("", PHARYNGEAL_EPIGLOTTAL, LATERAL_FRICATIVE, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_LATERAL_APPROXIMANT("", PHARYNGEAL_EPIGLOTTAL, LATERAL_APPROXIMANT),
    VOICED_PHARYNGEAL_EPIGLOTTAL_LATERAL_APPROXIMANT("", PHARYNGEAL_EPIGLOTTAL, LATERAL_APPROXIMANT, true),

    VOICELESS_PHARYNGEAL_EPIGLOTTAL_LATERAL_TAP_FLAP("", PHARYNGEAL_EPIGLOTTAL, LATERAL_TAP_FLAP),
    VOICED_PHARYNGEAL_EPIGLOTTAL_LATERAL_TAP_FLAP("", PHARYNGEAL_EPIGLOTTAL, LATERAL_TAP_FLAP, true),

    VOICELESS_GLOTTAL_STOP_PLOSIVE("", GLOTTAL, STOP_PLOSIVE),
    VOICED_GLOTTAL_STOP_PLOSIVE("", GLOTTAL, STOP_PLOSIVE, true),

    VOICELESS_GLOTTAL_NASAL("", GLOTTAL, NASAL),
    VOICED_GLOTTAL_NASAL("", GLOTTAL, NASAL, true),

    VOICELESS_GLOTTAL_FRICATIVE("", GLOTTAL, FRICATIVE),
    VOICED_GLOTTAL_FRICATIVE("", GLOTTAL, FRICATIVE, true),

    VOICELESS_GLOTTAL_APPROXIMANT("", GLOTTAL, APPROXIMANT),
    VOICED_GLOTTAL_APPROXIMANT("", GLOTTAL, APPROXIMANT, true),

    VOICELESS_GLOTTAL_TAP_OR_FLAP("", GLOTTAL, TAP_OR_FLAP),
    VOICED_GLOTTAL_TAP_OR_FLAP("", GLOTTAL, TAP_OR_FLAP, true),

    VOICELESS_GLOTTAL_TRILL("", GLOTTAL, TRILL),
    VOICED_GLOTTAL_TRILL("", GLOTTAL, TRILL, true),

    VOICELESS_GLOTTAL_LATERAL_FRICATIVE("", GLOTTAL, LATERAL_FRICATIVE),
    VOICED_GLOTTAL_LATERAL_FRICATIVE("", GLOTTAL, LATERAL_FRICATIVE, true),

    VOICELESS_GLOTTAL_LATERAL_APPROXIMANT("", GLOTTAL, LATERAL_APPROXIMANT),
    VOICED_GLOTTAL_LATERAL_APPROXIMANT("", GLOTTAL, LATERAL_APPROXIMANT, true),

    VOICELESS_GLOTTAL_LATERAL_TAP_FLAP("", GLOTTAL, LATERAL_TAP_FLAP),
    VOICED_GLOTTAL_LATERAL_TAP_FLAP("", GLOTTAL, LATERAL_TAP_FLAP, true),


}